version: "2.3"

volumes:
  db:
  data:

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    depends_on:
      - roundcube
      - roundcubenginx
    environment:
      - DOCKER_TEST_CONTAINER=roundcube
      - DOCKER_WEB_CONTAINER=roundcubenginx
    volumes_from:
      - roundcube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  roundcube:
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH}
      args:
        - TAG=${DOCKER_TAG}
    image: ${IMAGE_NAME}
    container_name: roundcube
    #restart: always
    depends_on:
      roundcubedb:
        condition: service_healthy
    links:
      - roundcubedb
    expose:
      - "9000"
    #ports:
    #  - "9090:9000"
    volumes:
      - data:/var/www/html
      #- /srv/roundcube/html:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as pgsql container name
      - ROUNDCUBEMAIL_DB_NAME=${ROUNDCUBE_DB_NAME}
      - ROUNDCUBEMAIL_DB_USER=${ROUNDCUBE_DB_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBE_DB_PWD}

  roundcubedb:
    image: postgres:latest
    container_name: roundcubedb
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${ROUNDCUBE_DB_USER}", "-d", "${ROUNDCUBE_DB_NAME}"]
      interval: 60s
      retries: 5
      #start-period: 10s
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - "5432"
    #ports:
    #  - "55432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      #- /srv/roundcube/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ROUNDCUBE_DB_NAME}
      - POSTGRES_USER=${ROUNDCUBE_DB_USER}
      - POSTGRES_PASSWORD=${ROUNDCUBE_DB_PWD}

  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    restart: always
    expose:
      - "80"
    #ports:
    #  - "8080:80"
    #  # If you need SSL connection
    #  - "8443:443"
    depends_on:
      - roundcube
    links:
      - roundcube
    volumes:
      - data:/var/www/html
      #- /srv/roundcube/html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      - NGINX_PHP_CGI=roundcube:9000 # same as roundcube container name
