dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - develop
    - master

before_install:
  - env | sort
  - dir="images/${VERSION}${VARIANT:+-$VARIANT}"

install:
  - cd "$dir"
  # Build project
  - ./hooks/run build

before_script:
  - docker images

script:
  - cd "$dir"
  # Execute project CI Tests
  - ./hooks/run test

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=1.3 VARIANT=fpm-alpine
    - env: VERSION=1.3 VARIANT=fpm
    - env: VERSION=1.3 VARIANT=apache

env: # Environments
    - VERSION=1.4 VARIANT=fpm-alpine
    - VERSION=1.4 VARIANT=fpm
    - VERSION=1.4 VARIANT=apache
