FROM roundcube/roundcubemail:%%VERSION%%%%VARIANT%%

LABEL maintainer="Mathieu BRUNOT <mathieu.brunot at monogramm dot io>"

# Add requirements for common extenions (untested so far)
RUN set -ex; \
	apk add --no-cache --virtual \
        libgpgme11 \
        libgpgme11-dev \
	; \
	\
    pecl install gnupg; \
    \
	docker-php-ext-enable gnupg; \
    \
    pear install Net_Sieve; \
    \
    pear install Net_LDAP3

VOLUME /var/roundcube/keys
