FROM roundcube/roundcubemail:%%VERSION%%%%VARIANT%%

LABEL maintainer="Mathieu BRUNOT <mathieu.brunot at monogramm dot io>"

# Add requirements for common extenions
RUN set -ex; \
	apt-get update; \
	\
	apt-get install -y --no-install-recommends \
        libgpgme11 \
        libgpgme11-dev \
        php-net-ldap3 \
	; \
	\
    pecl install gnupg; \
    \
	docker-php-ext-enable gnupg; \
    \
    pear install horde/Horde_ManageSieve

VOLUME /var/roundcube/keys
